# Generated by Django 3.2.5 on 2022-05-17 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CityBackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packing',
            new_name='Parking',
        ),
    ]
